BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAKPHTQEAAAAA%2B4W964LDmoCp9JK0wIDgoHgqCII%3DaTBk5uzfTsiMqJBqDEwH0qhvfqCoWviepg2GN5zAU1TwlD9q7W"
classes = ['negative', 'neutral', 'positive']
BINANCE_KEY = "Lq25ForxFzA0o9xSuy7bAIECix9cXrsbp8AeTzbXNG5WEOpncgI7gOiBW4hlrLOB"
BINANCE_SECRET = "kak2mADP6fZ73aczmjeShfpamUJfQzbHY8aT5PGmMKVzfM3RPe4jwyeiqmbxz9vl"